### ISSUE TITLE
Bot doesn't work after it is idle for a long time

### ISSUE THREAD

**Issue by nav-github01001** [EpikCord/EpikCord.py#113]
### Summary

Look Above

### Reproduction Steps

First run the bot,
then wait for 15-20 mins

### Expected Results

Bot to keep running

### Actual Results

Exception ignored in thread started by: <function EventHandler.ready.<locals>.heartbeater at 0x00000281CAB3CD30>
Traceback (most recent call last):
  File "C:\Users\navan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\EpikCord\__init__.py", line 831, in heartbeater
    loop.run_until_complete(self.heartbeat(False))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\navan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\EpikCord\__init__.py", line 924, in heartbeat  
    await self.send_json({"op": self.HEARTBEAT, "d": self.sequence or "null"})
  File "C:\Users\navan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\EpikCord\__init__.py", line 956, in send_json  
    await self.ws.send_json(json)
  File "C:\Users\navan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\aiohttp\client_ws.py", line 164, in send_json  
    await self.send_str(dumps(data), compress=compress)
  File "C:\Users\navan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\aiohttp\client_ws.py", line 150, in send_str   
    await self._writer.send(data, binary=False, compress=compress)
LocalCache\local-packages\Python310\site-packages\aiohttp\http_websocket.py", line 687, in send    await self._send_frame(message, WSMsgType.TEXT, compress)
  File "C:\Users\navan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\aiohttp\http_websocket.py", line 598, in _send_frame    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport

### Intents

Any

### System Information

Name: EpikCord.py
Version: 0.4.13.3
Summary: A Modern API wrapper for Discord.
Home-page: https://github.com/EpikCord/EpikCord.py
Author: EpikCord
Author-email:
License: MIT
Location: c:\users\navan\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
Requires:
Required-by: 

### Checklist

- [X] This bug was found on the latest version of EpikCord
- [X] You have checked that there is no issue already mentioning this bug, open or closed
- [X] Full details of the bug have been provided/shown, including full tracebacks in case of exceptions
- [X] All bot tokens have been hidden/omitted from any screenshots or code, if any

**Comment by Jerrydotpy** [comment]
Will this be closed to rewrite @TheUntraceable

**Comment by TheUntraceable** [comment]
This was fixed, forgot to mention it
