### ISSUE TITLE
Docs not backing up

### ISSUE THREAD

**Issue by nav-github01001** [EpikCord/EpikCord.py#165]
### Summary

^

### Reproduction Steps

There is a improper setting of docs webhook

### Expected Results

Backup

### Actual Results

Docs failing

### Intents

/

### System Information

\

### Checklist

- [X] This bug was found on the latest version of EpikCord
- [X] You have checked that there is no issue already mentioning this bug, open or closed
- [X] Full details of the bug have been provided/shown, including full tracebacks in case of exceptions
- [X] All bot tokens have been hidden/omitted from any screenshots or code, if any

### Additional Context

![Screenshot_20220619-172514_Chrome](https://user-images.githubusercontent.com/78836383/174479739-7dec7d0b-c7d8-4d3a-8c71-5a31f2a518bc.jpg)

**Comment by TheUntraceable** [comment]
![image](https://user-images.githubusercontent.com/73362400/174629790-d9710d86-17f0-4ba3-9974-5c931915202c.png)
It works and always has been working. Build fails.

**Comment by TheUntraceable** [comment]
Running Sphinx v5.0.2
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 3 source files that are out of date
updating environment: [new config] 3 added, 0 changed, 0 removed
reading sources... [ 33%] source/EpikCord
reading sources... [ 66%] source/EpikCord.managers
reading sources... [100%] source/index

/home/docs/checkouts/readthedocs.org/user_builds/epikcordpy/checkouts/latest/docs/source/EpikCord.rst:18: ERROR: Unknown directive type "automodule".

.. automodule:: EpikCord.components
   :members:
   :undoc-members:
   :show-inheritance:
/home/docs/checkouts/readthedocs.org/user_builds/epikcordpy/checkouts/latest/docs/source/EpikCord.rst:26: ERROR: Unknown directive type "automodule".

.. automodule:: EpikCord.exceptions
   :members:
   :undoc-members:
   :show-inheritance:
/home/docs/checkouts/readthedocs.org/user_builds/epikcordpy/checkouts/latest/docs/source/EpikCord.rst:34: ERROR: Unknown directive type "automodule".

.. automodule:: EpikCord.options
   :members:
   :undoc-members:
   :show-inheritance:
/home/docs/checkouts/readthedocs.org/user_builds/epikcordpy/checkouts/latest/docs/source/EpikCord.rst:42: ERROR: Unknown directive type "automodule".

.. automodule:: EpikCord.partials
   :members:
   :undoc-members:
   :show-inheritance:
/home/docs/checkouts/readthedocs.org/user_builds/epikcordpy/checkouts/latest/docs/source/EpikCord.rst:50: ERROR: Unknown directive type "automodule".

.. automodule:: EpikCord
   :members:
   :undoc-members:
   :show-inheritance:
/home/docs/checkouts/readthedocs.org/user_builds/epikcordpy/checkouts/latest/docs/source/EpikCord.managers.rst:10: ERROR: Unknown directive type "automodule".

.. automodule:: EpikCord.managers.cache_manager
   :members:
   :undoc-members:
   :show-inheritance:
/home/docs/checkouts/readthedocs.org/user_builds/epikcordpy/checkouts/latest/docs/source/EpikCord.managers.rst:18: ERROR: Unknown directive type "automodule".

.. automodule:: EpikCord.managers.channel_manager
   :members:
   :undoc-members:
   :show-inheritance:
/home/docs/checkouts/readthedocs.org/user_builds/epikcordpy/checkouts/latest/docs/source/EpikCord.managers.rst:26: ERROR: Unknown directive type "automodule".

.. automodule:: EpikCord.managers.guilds_manager
   :members:
   :undoc-members:
   :show-inheritance:
/home/docs/checkouts/readthedocs.org/user_builds/epikcordpy/checkouts/latest/docs/source/EpikCord.managers.rst:34: ERROR: Unknown directive type "automodule".

.. automodule:: EpikCord.managers.member_manager
   :members:
   :undoc-members:
   :show-inheritance:
/home/docs/checkouts/readthedocs.org/user_builds/epikcordpy/checkouts/latest/docs/source/EpikCord.managers.rst:42: ERROR: Unknown directive type "automodule".

.. automodule:: EpikCord.managers.roles_manager
   :members:
   :undoc-members:
   :show-inheritance:
/home/docs/checkouts/readthedocs.org/user_builds/epikcordpy/checkouts/latest/docs/source/EpikCord.managers.rst:50: ERROR: Unknown directive type "automodule".

.. automodule:: EpikCord.managers
   :members:
   :undoc-members:
   :show-inheritance:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/epikcordpy/envs/latest/lib/python3.9/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/epikcordpy/envs/latest/lib/python3.9/site-packages/sphinx/application.py", line 329, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/epikcordpy/envs/latest/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 288, in build_update
    self.build(to_build,
  File "/home/docs/checkouts/readthedocs.org/user_builds/epikcordpy/envs/latest/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 302, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/epikcordpy/envs/latest/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 412, in read
    raise SphinxError('root file %s not found' %
sphinx.errors.SphinxError: root file /home/docs/checkouts/readthedocs.org/user_builds/epikcordpy/checkouts/latest/docs/index.rst not found

Sphinx error:
root file /home/docs/checkouts/readthedocs.org/user_builds/epikcordpy/checkouts/latest/docs/index.rst not found

**Comment by nav-github01001** [comment]
...
