### ISSUE TITLE
HTTPClient is broken.

### ISSUE THREAD

**Issue by TheUntraceable** [EpikCord/EpikCord.py#166]
### Summary

Because it inherits from ClientSession, ws_connect doesn't work for some reason.

### Reproduction Steps

Try run a bot

### Expected Results

To connect to the websocket.

### Actual Results

Task exception was never retrieved
future: <Task finished name='Task-1' coro=<WebsocketClient.login.<locals>.runner() done, defined at C:\Users\i5\Documents\Programming\Github\EpikCord.py\EpikCord\__init__.py:1177> exception=TypeError("object NoneType can't be used in 'await' expression")>
Traceback (most recent call last):
  File "C:\Users\i5\Documents\Programming\Github\EpikCord.py\EpikCord\__init__.py", line 1179, in runner
    await self.connect()
  File "C:\Users\i5\Documents\Programming\Github\EpikCord.py\EpikCord\__init__.py", line 1116, in connect
    self.ws = await self.http.ws_connect(
  File "C:\Users\i5\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 776, in _ws_connect
    resp = await self.request(
  File "C:\Users\i5\Documents\Programming\Github\EpikCord.py\EpikCord\__init__.py", line 1998, in request
    await bucket.lock.release()
TypeError: object NoneType can't be used in 'await' expression
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x000002F6348A2A10>
transport: <_ProactorSocketTransport fd=652 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "C:\Users\i5\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 690, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Users\i5\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 361, in write
    self._loop_writing(data=bytes(data))
  File "C:\Users\i5\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 397, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
Exception ignored in: <function ClientResponse.__del__ at 0x000002F634735EA0>
Traceback (most recent call last):
  File "C:\Users\i5\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client_reqrep.py", line 810, in __del__
    self._connection.release()
  File "C:\Users\i5\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 178, in release
    self._connector._release(
  File "C:\Users\i5\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 665, in _release
    protocol.close()
  File "C:\Users\i5\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client_proto.py", line 63, in close
    transport.close()
  File "C:\Users\i5\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 316, in close
    self._ssl_protocol._start_shutdown()
  File "C:\Users\i5\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 599, in _start_shutdown
    self._write_appdata(b'')
  File "C:\Users\i5\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 604, in _write_appdata
    self._process_write_backlog()
  File "C:\Users\i5\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 712, in _process_write_backlog
    self._fatal_error(exc, 'Fatal error on SSL transport')
  File "C:\Users\i5\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 726, in _fatal_error
    self._transport._force_close(exc)
  File "C:\Users\i5\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 151, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "C:\Users\i5\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Users\i5\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Unclosed client session
client_session: <EpikCord.HTTPClient object at 0x000002F631D3F730>

### Intents

Irrelevant

### System Information

Name: EpikCord.py
Version: 0.4.13.3
Summary: A Modern API wrapper for Discord.
Home-page: https://github.com/EpikCord/EpikCord.py
Author: EpikCord
Author-email:
License: MIT
Location: c:\users\i5\appdata\local\programs\python\python310\lib\site-packages
Requires:
Required-by:

### Checklist

- [X] This bug was found on the latest version of EpikCord
- [X] You have checked that there is no issue already mentioning this bug, open or closed
- [X] Full details of the bug have been provided/shown, including full tracebacks in case of exceptions
- [X] All bot tokens have been hidden/omitted from any screenshots or code, if any

**Comment by nav-github01001** [comment]
Something wrong in ratelimit handler

**Comment by TheUntraceable** [comment]
Forgot to mention that.

**Comment by TheUntraceable** [comment]
Maybe add an exception for urls with ws: at the start

**Comment by nav-github01001** [comment]
Yes maybe

**Comment by TheUntraceable** [comment]
Solved.
