### ISSUE TITLE
Error: AttributeError: 'Client' object has no attribute 'ws'

### ISSUE THREAD

**Issue by nav-github01001** [EpikCord/EpikCord.py#66]
### Summary

AttributeError: 'Client' object has no attribute 'ws'

### Reproduction Steps

I just ran the bot, when it tried to login it gave an error 
Note: I had to remove from .managers import * because it threw an image
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<WebsocketClient.login.<locals>.runner() done, defined at C:\FalconFiles\FalconTestVenv\lib\site-packages\EpikCord\__init__.py:472> exception=AttributeError("'Client' object has no attribute 'ws'")>
Traceback (most recent call last):
  File "C:\FalconFiles\FalconTestVenv\lib\site-packages\aiohttp\connector.py", line 1154, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "C:\FalconFiles\FalconTestVenv\lib\site-packages\aiohttp\connector.py", line 880, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "C:\FalconFiles\FalconTestVenv\lib\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 855, in getaddrinfo
    return await self.run_in_executor(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\FalconFiles\FalconTestVenv\lib\site-packages\EpikCord\__init__.py", line 474, in runner
    await self.connect()
  File "C:\FalconFiles\FalconTestVenv\lib\site-packages\EpikCord\__init__.py", line 415, in connect
    self.ws = await self.session.ws_connect("wss://gateway.discord.gg/?v=9&encoding=json")    
  File "C:\FalconFiles\FalconTestVenv\lib\site-packages\aiohttp\client.py", line 776, in _ws_connect
    resp = await self.request(
  File "C:\FalconFiles\FalconTestVenv\lib\site-packages\aiohttp\client.py", line 535, in _request
    conn = await self._connector.connect(
  File "C:\FalconFiles\FalconTestVenv\lib\site-packages\aiohttp\connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\FalconFiles\FalconTestVenv\lib\site-packages\aiohttp\connector.py", line 907, in _c  File "C:\FalconFiles\FalconTestVenv\lib\site-packages\EpikCord\__init__.py", line 458, in close
    if self.ws is not None:AttributeError: 'Client' object has no attribute 'ws'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001A9FFE0BAF0>Unclosed client session
client_session: <EpikCord.HTTPClient object at 0x000001A9FFE0A290>

### Minimal Reproducible Code

```python
"""
Before you implement this in your bot, please note that its just for testing, 
If you have a test bot and are professional with your code, you can experiment 
with different features and report the bugs in an issue
"""


from EpikCord import Client,Intents,Messageable, Embed

intents = Intents().guilds.guild_members.guild_messages.direct_messages

client = Client("my_token", intents)

@client.event
async def message_create(message):
    if message.author.id == client.user.id:
        return
    if message.content == "example test":
        message.channel = Messageable(client, message.channel_id)

        await message.channel.send(content="hello, chat testing")

client.login()
```

### Expected Results

bot to run

### Actual Results

error messages

### Intents

.guilds.guild_members.guild_messages.direct_messages

### System Information

Name: EpikCord.py
Version: 0.4.3
Summary: A Modern API wrapper for Discord, Intended for replacement of the now discontinued Discord.py library
Home-page: https://github.com/EpikHost/EpikCord.py
Author: EpikHost
Author-email: support@epikhost.xyz
License: MIT
Location: c:\falconfiles\falcontestvenv\lib\site-packages
Requires: aiohttp, websocket-client
Required-by:

### Checklist

- [X] This bug was found on the latest version of EpikCord
- [X] You have checked that there is no issue already mentioning this bug, open or closed
- [X] Full details of the bug have been provided/shown, including full tracebacks in case of exceptions
- [X] All bot tokens have been hidden/omitted from any screenshots or code, if any

### Additional Context

we are gonna fix it

**Comment by nav-github01001** [comment]
@Jerry-py @TheUntraceable please look into this

**Comment by nav-github01001** [comment]
I forgot my parents blocked me from using discord so i use opera gx vpn. my bad
